from urllib import response

import streamlit as st
import datetime
import requests
import json
import sys

BASE_URL = "http://localhost:8000" 

st.set_page_config(
    page_title="Travel Planner Application",
    page_icon=":airplane:",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("Agentic Travel Planner Application")


#  @initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

st.header("How can I assist you with your travel plans today?")

with st.form():
    user_input = st.text_input("User Input",placeholder= "e.g., Plan a 5-day trip to Paris in June,")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:
        # show user msg
        # # show thinking spinner while waiting for response
        with st.spinner("Thinking..."):
            payload = {"Question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)
        if response.status_code == 200:
            answer = response.json().get("answer", "No answer received.")
            markdown_content = f"""#AI Travel Plan
            # **Generated :** {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
            # **Created by :** Travel Planner Application
            ---
            {answer}
            ---
            *This content was generated by the Travel Planner Application using an AI model.*

            """

            st.markdown(markdown_content)
        else:
            st.error("AI model failed to generate a response. Please try again later. " + response.text)

    except Exception as e:
        raise f"The response failed due to {e}"
